version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: arenax-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - arenax

  backend:
    build: ./backend
    container_name: arenax-backend
    restart: always
    environment:
      PORT: 5000
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/arenax?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRE: 7d
      CORS_ORIGIN: http://98.80.100.61  
      EMAIL_USER: arenasupprt@gmail.com
      EMAIL_PASS: "tszm iaqj nbmq rocd"
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - arenax

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arenax-admin
    restart: always
    environment:
      VITE_API_BASE_URL: http://98.80.100.61:5000/api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - arenax

volumes:
  mongo_data:

networks:
  arenax:
    driver: bridge
